version: "3"
services:
  db:
    image: mysql:5.7
    command: [ #使用 command 可以覆盖容器启动后默认执行的命令
      '--character-set-server=utf8mb4', #设置数据库表的数据集
      '--collation-server=utf8mb4_unicode_ci', #设置数据库表的数据集
    ]
    volumes:
      - "./mysql:/var/lib/mysql"
      - "./sql:/code/sql"
    ports:
      - "3306:3306"
    restart: always
    networks:
      - db_network
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_DATABASE=django_app
  redis:
    image: redis:3.2.1
    ports:
      - "6379:6379"
    networks:
      - db_network
  app:
    restart: always
    build:
      context: ../
      dockerfile: ./deploy/django_container/Dockerfile

    command: bash -c "python3 manage.py collectstatic --no-input && python3 manage.py migrate && gunicorn --timeout=30 --workers=4 --bind :8000 blog_django.wsgi:application"
    volumes:
      - ..:/code
      - static-volume:/code/collected_static
    expose:
      - "8000"
    depends_on:
      - db
    networks:
      - db_network
      - web_network
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:8000"
    volumes:
      - static-volume:/code/collected_static
      - ./config/nignx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
  db_network:
    driver: bridge

volumes:
  static-volume: